include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-pslinkb
PKG_RELEASE:=1
PKG_LICENSE:=MIT OR Apache-2.0
PKG_MAINTAINER:=Urlynn

LUCI_TITLE:=PSLinkB - PS5 to Bilibili Live Bridge
LUCI_DESCRIPTION:=LuCI interface for PSLinkB
LUCI_DEPENDS:=+luci-lib-uqr
LUCI_PKGARCH:=all

include ../../luci.mk
