include $(TOPDIR)/rules.mk

PKG_NAME:=pslinkb
PKG_VERSION:=0.2.5
PKG_RELEASE:=1

PKG_LICENSE:=MIT OR Apache-2.0
PKG_MAINTAINER:=Urlynn

PKG_BUILD_DEPENDS:=rust/host

include $(INCLUDE_DIR)/package.mk

define Package/pslinkb
  SECTION:=multimedia
  CATEGORY:=Multimedia
  TITLE:=PS5 to Bilibili Live Bridge
  URL:=https://github.com/urlynn/PSLinkB
endef

define Package/pslinkb/description
  PS5 to Bilibili live streaming bridge with RTMP relay and danmaku forwarding.
endef

define Build/Prepare
	# Prepare
endef

define Build/Compile
	# Build
endef

define Package/pslinkb/install
	# Install
endef

$(eval $(call BuildPackage,pslinkb))
